{{- if not .Values.mealie.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie-backup.fullname" . }}-token
type: Opaque
stringData:
  token: {{ .Values.mealie.token | default "" | quote }}
{{- end -}}
