apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie-backup.fullname" . }}-token
type: Opaque
stringData:
  # Base64 encoded or cleartext depending on how it's provided.
  # Here we use cleartext via Helm values or set-string.
  token: {{ .Values.mealie.token | default "" | quote }}
